// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "nativium/game/NTVGameApplicationCore+Private.h"
#import "nativium/game/NTVGameApplicationCore.h"
#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface NTVGameApplicationCore ()

- (id)initWithCpp:(const std::shared_ptr<::nativium::game::ApplicationCore>&)cppRef;

@end

@implementation NTVGameApplicationCore {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::nativium::game::ApplicationCore>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::nativium::game::ApplicationCore>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable NTVGameApplicationCore *)shared {
    try {
        auto objcpp_result_ = ::nativium::game::ApplicationCore::shared();
        return ::djinni_generated::ApplicationCore::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getVersion {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getVersion();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)initialize:(int32_t)width
            height:(int32_t)height
              mode:(int32_t)mode {
    try {
        _cppRefHandle.get()->initialize(::djinni::I32::toCpp(width),
                                        ::djinni::I32::toCpp(height),
                                        ::djinni::I32::toCpp(mode));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto ApplicationCore::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto ApplicationCore::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<NTVGameApplicationCore>(cpp);
}

}  // namespace djinni_generated

@end
