// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni


export interface ApplicationCore {
    getVersion(): string;
    initialize(width: number, height: number, mode: number): void;
}
export interface ApplicationCore_statics {
    shared(): ApplicationCore;
}

export interface Game_statics {
    ApplicationCore: ApplicationCore_statics;
}
