// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "nativium/game/NTVGameApplicationCore.hpp"  // my header

namespace djinni_generated {

em::val NTVGameApplicationCore::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getVersion",
        "initialize",
    });
    return methods;
}

em::val NTVGameApplicationCore::shared() {
    try {
        auto r = ::nativium::game::ApplicationCore::shared();
        return ::djinni_generated::NTVGameApplicationCore::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni_generated::NTVGameApplicationCore>::handleNativeException(e);
    }
}
std::string NTVGameApplicationCore::getVersion(const CppType& self) {
    try {
        auto r = self->getVersion();
        return ::djinni::String::fromCpp(r);
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<::djinni::String>::handleNativeException(e);
    }
}
void NTVGameApplicationCore::initialize(const CppType& self, int32_t w_width,int32_t w_height,int32_t w_mode) {
    try {
        self->initialize(::djinni::I32::toCpp(w_width),
                   ::djinni::I32::toCpp(w_height),
                   ::djinni::I32::toCpp(w_mode));
    }
    catch(const std::exception& e) {
        return djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(nativium_game_application_core) {
    em::class_<::nativium::game::ApplicationCore>("ApplicationCore")
        .smart_ptr<std::shared_ptr<::nativium::game::ApplicationCore>>("ApplicationCore")
        .function("nativeDestroy", &NTVGameApplicationCore::nativeDestroy)
        .class_function("shared", NTVGameApplicationCore::shared)
        .function("getVersion", NTVGameApplicationCore::getVersion)
        .function("initialize", NTVGameApplicationCore::initialize)
        ;
}

}  // namespace djinni_generated
