// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/wasm/djinni_wasm.hpp"
#include "nativium/game/ApplicationCore.hpp"

namespace djinni_generated {

struct NTVGameApplicationCore : ::djinni::JsInterface<::nativium::game::ApplicationCore, NTVGameApplicationCore> {
    using CppType = std::shared_ptr<::nativium::game::ApplicationCore>;
    using CppOptType = std::shared_ptr<::nativium::game::ApplicationCore>;
    using JsType = em::val;
    using Boxed = NTVGameApplicationCore;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        djinni::checkForNull(c.get(), "NTVGameApplicationCore::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val shared();
    static std::string getVersion(const CppType& self);
    static void initialize(const CppType& self, int32_t w_width,int32_t w_height,int32_t w_mode);

};

}  // namespace djinni_generated
