// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "nativium/game/ApplicationCore.hpp"

namespace djinni_generated {

class NTVGameApplicationCore final : ::djinni::JniInterface<::nativium::game::ApplicationCore, NTVGameApplicationCore> {
public:
    using CppType = std::shared_ptr<::nativium::game::ApplicationCore>;
    using CppOptType = std::shared_ptr<::nativium::game::ApplicationCore>;
    using JniType = jobject;

    using Boxed = NTVGameApplicationCore;

    ~NTVGameApplicationCore();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NTVGameApplicationCore>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NTVGameApplicationCore>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NTVGameApplicationCore();
    friend ::djinni::JniClass<NTVGameApplicationCore>;
    friend ::djinni::JniInterface<::nativium::game::ApplicationCore, NTVGameApplicationCore>;

};

}  // namespace djinni_generated
